name: Build Windows
on:
  push:
    branches: [ gh-actions ]
  pull_request:
    branches: [ gh-actions ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - run: go version
    
    - run: go mod tidy && git diff --exit-code go.mod go.sum

#     - name: Setup upterm session
#       uses: lhotari/action-upterm@v1
      
    - run: |
        $env:GOARCH = 386 
        $env:GOOS = 'windows' 
        go build -tags="forceposix" -o out/cf-cli_win32.exe -ldflags "-w -s	-X code.cloudfoundry.org/cli/version.binarySHA=123 -X code.cloudfoundry.org/cli/version.binaryBuildDate=1-1-1901 -X code.cloudfoundry.org/cli/version.binaryVersion=999" .

    - run: out/cf-cli_win32.exe version
