name: Go

on:
  push:
    branches: [ gh-actions ]
  pull_request:
    branches: [ gh-actions ]

jobs:

  build:
    runs-on: mac-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - run: go version
    - run: go mod tidy && git diff --exit-code go.mod go.sum
    - run: go get -u github.com/onsi/ginkgo/ginkgo

    - uses: actions/cache@v2
      with:
        # In order:
        # * Module download cache
        # * Build cache (Linux)
        # * Build cache (Mac)
        # * Build cache (Windows)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
      
#     - name: Setup upterm session
#       uses: lhotari/action-upterm@v1
      
    - name: Unit Tests
      run: ginkgo -r -randomizeAllSpecs -requireSuite  -randomizeSuites -p -skipPackage integration,cf/ssh,plugin,cf/actors/plugin,cf/commands/plugin,cf/actors/plugin,util/randomword
