name: Go

on:
  push:
    branches: [ gh-actions ]
  pull_request:
    branches: [ gh-actions ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Setup
      run: |
        go version
        go list -m

    - run: go mod tidy && git diff --exit-code go.mod go.sum
    - run: go vet ./...

    - name: Build
      run: make build

    - name: Test
      run: go run ./ginkgo -r --randomizeAllSpecs --randomizeSuites --race --trace
